Vagrant.configure(2) do |config|
    config.vm.define "terraform" do |terraform|
        terraform.vm.box = "ubuntu/xenial64"
            terraform.vm.hostname = "terraform"
            terraform.vm.provision "shell", path: "scripts/install.sh"
            terraform.vm.provider "virtualbox" do |v|
              v.memory = 4096
              v.cpus = 2
            end
    end
end
